//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.26 at 12:48:35 PM CEST 
//


package xlike.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sentences" type="{}sentenceList" minOccurs="0"/>
 *         &lt;element name="entities" type="{}entityList" minOccurs="0"/>
 *         &lt;element name="conll" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item", propOrder = {
    "sentences",
    "entities",
    "conll"
})
@XmlRootElement
public class Item {

    protected SentenceList sentences;
    protected EntityList entities;
    protected String conll;

    /**
     * Gets the value of the sentences property.
     * 
     * @return
     *     possible object is
     *     {@link SentenceList }
     *     
     */
    public SentenceList getSentences() {
        return sentences;
    }

    /**
     * Sets the value of the sentences property.
     * 
     * @param value
     *     allowed object is
     *     {@link SentenceList }
     *     
     */
    public void setSentences(SentenceList value) {
        this.sentences = value;
    }

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link EntityList }
     *     
     */
    public EntityList getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityList }
     *     
     */
    public void setEntities(EntityList value) {
        this.entities = value;
    }

    /**
     * Gets the value of the conll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConll() {
        return conll;
    }

    /**
     * Sets the value of the conll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConll(String value) {
        this.conll = value;
    }

}
